# Site settings
title: Vinicius Oliveira
description: Personal Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://viniciusoliveira.dev" # o nome do host e protocolo base do seu site.

# User settings
username: Vinicius Oliveira
user_description: Software developer passionate about creating innovative and efficient solutions. 
Combining modern design with robust functionality, I strive to turn ideas into impactful digital experiences. 
Enthusiast of clean code, best practices, and emerging technologies.
user_title: Software Developer
email: violiveira.dev@gmail.com
twitter_username: violiveiradev
github_username: violiveiradev
linkedin_username: violiveiradev

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

languages:
  - code: en
    name: English
  - code: pt
    name: Português
