# Site settings
title: Vinicius Oliveira
description: Personal Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://viniciusoliveira.dev" # o nome do host e protocolo base do seu site.

# User settings
username: Vinicius Oliveira
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: violiveira.dev@gmail.com
twitter_username: violiveiradev
github_username: violiveiradev
linkedin_username: violiveiradev

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

languages:
  - code: en
    name: English
  - code: pt
    name: Português
